spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fashion_store?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update        # tự tạo bảng khi chạy
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: f64f841677e6a3
    password: 6e26a428f6aaab   # thay bằng password thật
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: sandbox.smtp.mailtrap.io

server:
  port: 8080

app:
  jwt:
    secret: fashionstore_super_secret_key_2024_do_not_share
    expiration: 900000   # 1 ngày (ms)
  order:
    shipping-fee: 30000
  upload:
    dir: uploads
    public-path: /uploads
